# getextrapoints.admin - uprawnienia admina
# eshop.use - /eshop - dostep
# /ep give {nick} {ilosc}
# /ep set {nick} {ilosc}
mysql:
  host: localhost
  username: root
  password: ""
  database: database
  port: 3306
  ssl: false

# wlaczenie/wylaczenie wymaga restartu serwera
auto-money:
  enable: true
  # czas w sekundach
  time: 10
  # ile extrapoints ma dodawac
  value: 0.5


kill-player:
  enable: true
  # czas w sekundach
  # co ile moze zabijac tego samego gracza
  time: 3600
  value: 5.0

inv:
  size: 54
  title: "&0Sklep za extrapoints"
  background:
    '1':
      material: BLACK_STAINED_GLASS_PANE
      displayname: "&7 "
      lore: []
      slots: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53]

lang:
  balance: "&eExtraPoints: &f{balance}"
  new-balance: "&eNowe saldo: &f{balance}"
  no-balance: "&cNie posiadasz tyle extrapoints!"
  success-buy: "&aPomyslnie kupiono {name}!"
  kill-money: "&cOtrzymales {price} za zabicie {player}!"
  get-money: "&aOtrzymales {price} za granie za serwerze!"